# Generated by Django 4.2.1 on 2023-05-21 12:50

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='user',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(blank=True, max_length=20)),
                ('sobrenome', models.CharField(max_length=20)),
                ('cpf', models.CharField(blank=True, max_length=14)),
                ('telefone', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=50)),
                ('data_nascimento', models.DateField(max_length=8)),
                ('data_criacao', models.DateTimeField(default=django.utils.timezone.now)),
                ('usuario', models.CharField(blank=True, max_length=20)),
                ('senha', models.CharField(blank=True, max_length=16)),
            ],
        ),
    ]
