# Generated by Django 4.2.1 on 2023-05-21 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_user_inativo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='sobrenome',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
