# Generated by Django 4.2.1 on 2023-05-21 16:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_user_sobrenome'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='user',
            new_name='usuario',
        ),
    ]
