# Generated by Django 4.2.1 on 2023-05-21 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_rename_usuario_usuarios'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuarios',
            name='nome',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='usuarios',
            name='sobrenome',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
